'use strict'

angular.module('GMClient')
  .factory('PluginEngines', function () {
    return function () {
      return [
        '1-ecommerce',
        '1ShoppingCart',
        '3dcart',
        'AAcart.com',
        'Ablecommerce',
        'Afcommerce',
        'Agoracart',
        'ATG',
        'Avactis',
        'BigCommerce',
        'Bizshoppingcart',
        'Bosscart',
        'Clickartpro',
        'Clicshop',
        'Contentshelf',
        'CoreCommerce',
        'CREloaded',
        'CS-Cart',
        'CubeCart',
        'Digistore',
        'Ecartsoft',
        'Ecmidas',
        'Ecommercetemplates',
        'ECrater',
        'ECShop',
        'Ecwid',
        'Elastic Path',
        'Fastspring',
        'Fat Free Cart',
        'Fortune3 Ecommerce Software',
        'FoxyCart',
        'GetShopped',
        'GoDaddy Quick Cart',
        'GoEmerchant.com',
        'IBM Web Sphare',
        'Instantestore',
        'Interspire',
        'King Cart',
        'Kryptronic',
        'Lite Commerce',
        'Merchandizer.com',
        'Mivamerchant',
        'Monstercommerce',
        'Neto',
        'NetworkSolutions.com',
        'Nexternal',
        'Opencart',
        'OsCommerce',
        'Oscworks',
        'Ozcart',
        'Payfast',
        'Pdgsoft',
        'Pinnaclecart',
        'Productcart',
        'Rapidshop',
        'Searchfit',
        'Sellerdeck',
        'Seo-cart',
        'Shopbuilder',
        'Shopfactory',
        'ShopperPress',
        'Shopping Cart Elite',
        'Shopsite',
        'SmallBusiness.Yahoo.com',
        'Spree Commerce',
        'Squirrel Cart',
        'StroreFront.net',
        'Summercart',
        'Sunshop',
        'Tomato Cart',
        'Turnkeywebtools',
        'Ubercart',
        'Ultracart',
        'Uniecommerce',
        'Vendio',
        'Vevocart',
        'Viart',
        'Virtuemart',
        'Volusion',
        'Vpasp',
        'WordPress E-Commerce',
        'WP eStore',
        'X-Cart',
        'Yahoo! Ecommerce',
        'Zen Cart',
        'Zeuscart',
        'LemonStand',
        'SquareSpace',
        'AmeriCommerce',
        'BigCartel',
        'WIX',
        'Weebly',
        'Web.com',
        'Etsy'
      ]
    }
  })
