'use strict'
/* global _ */

angular.module('GMClient')

  .factory('BillingCountriesService', function () {
    var countries = [
      { slug: 'AC', label: 'Ascension Island' },
      { slug: 'AD', label: 'Andorra' },
      { slug: 'AE', label: 'United Arab Emirates' },
      { slug: 'AF', label: 'Afghanistan' },
      { slug: 'AG', label: 'Antigua and Barbuda' },
      { slug: 'AI', label: 'Anguilla' },
      { slug: 'AL', label: 'Albania' },
      { slug: 'AM', label: 'Armenia' },
      { slug: 'AN', label: 'Netherlands Antilles' },
      { slug: 'AO', label: 'Angola' },
      { slug: 'AQ', label: 'Antarctica' },
      { slug: 'AR', label: 'Argentina' },
      { slug: 'AS', label: 'American Samoa' },
      { slug: 'AT', label: 'Austria', isEU: true },
      { slug: 'AU', label: 'Australia' },
      { slug: 'AW', label: 'Aruba' },
      { slug: 'AX', label: 'Åland Islands' },
      { slug: 'AZ', label: 'Azerbaijan' },
      { slug: 'BA', label: 'Bosnia and Herzegovina' },
      { slug: 'BB', label: 'Barbados' },
      { slug: 'BD', label: 'Bangladesh' },
      { slug: 'BE', label: 'Belgium', isEU: true },
      { slug: 'BF', label: 'Burkina Faso' },
      { slug: 'BG', label: 'Bulgaria', isEU: true },
      { slug: 'BH', label: 'Bahrain' },
      { slug: 'BI', label: 'Burundi' },
      { slug: 'BJ', label: 'Benin' },
      { slug: 'BL', label: 'Saint Barthélemy' },
      { slug: 'BM', label: 'Bermuda' },
      { slug: 'BN', label: 'Brunei' },
      { slug: 'BO', label: 'Bolivia' },
      { slug: 'BQ', label: 'British Antarctic Territory' },
      { slug: 'BR', label: 'Brazil' },
      { slug: 'BS', label: 'Bahamas' },
      { slug: 'BT', label: 'Bhutan' },
      { slug: 'BV', label: 'Bouvet Island' },
      { slug: 'BW', label: 'Botswana' },
      { slug: 'BY', label: 'Belarus' },
      { slug: 'BZ', label: 'Belize' },
      { slug: 'CA', label: 'Canada' },
      { slug: 'CC', label: 'Cocos [Keeling] Islands' },
      { slug: 'CD', label: 'Congo - Kinshasa' },
      { slug: 'CD', label: 'Congo [DRC]' },
      { slug: 'CF', label: 'Central African Republic' },
      { slug: 'CG', label: 'Congo - Brazzaville' },
      { slug: 'CG', label: 'Congo [Republic]' },
      { slug: 'CH', label: 'Switzerland' },
      { slug: 'CI', label: 'Côte d’Ivoire' },
      { slug: 'CI', label: 'Ivory Coast' },
      { slug: 'CK', label: 'Cook Islands' },
      { slug: 'CL', label: 'Chile' },
      { slug: 'CM', label: 'Cameroon' },
      { slug: 'CN', label: 'China' },
      { slug: 'CO', label: 'Colombia' },
      { slug: 'CP', label: 'Clipperton Island' },
      { slug: 'CR', label: 'Costa Rica' },
      { slug: 'CS', label: 'Serbia and Montenegro' },
      { slug: 'CT', label: 'Canton and Enderbury Islands' },
      { slug: 'CU', label: 'Cuba' },
      { slug: 'CV', label: 'Cape Verde' },
      { slug: 'CX', label: 'Christmas Island' },
      { slug: 'CY', label: 'Cyprus', isEU: true },
      { slug: 'CZ', label: 'Czech Republic', isEU: true },
      { slug: 'DE', label: 'Germany', isEU: true },
      { slug: 'DG', label: 'Diego Garcia' },
      { slug: 'DJ', label: 'Djibouti' },
      { slug: 'DK', label: 'Denmark', isEU: true },
      { slug: 'DM', label: 'Dominica' },
      { slug: 'DO', label: 'Dominican Republic' },
      { slug: 'DZ', label: 'Algeria' },
      { slug: 'EA', label: 'Ceuta and Melilla' },
      { slug: 'EC', label: 'Ecuador' },
      { slug: 'EE', label: 'Estonia', isEU: true },
      { slug: 'EG', label: 'Egypt' },
      { slug: 'EH', label: 'Western Sahara' },
      { slug: 'ER', label: 'Eritrea' },
      { slug: 'ES', label: 'Spain', isEU: true },
      { slug: 'ET', label: 'Ethiopia' },
      { slug: 'FI', label: 'Finland', isEU: true },
      { slug: 'FJ', label: 'Fiji' },
      { slug: 'FK', label: 'Falkland Islands' },
      { slug: 'FK', label: 'Falkland Islands [Islas Malvinas]' },
      { slug: 'FM', label: 'Micronesia' },
      { slug: 'FO', label: 'Faroe Islands' },
      { slug: 'FQ', label: 'French Southern and Antarctic Territories' },
      { slug: 'FR', label: 'France', isEU: true },
      { slug: 'FX', label: 'Metropolitan France' },
      { slug: 'GA', label: 'Gabon' },
      { slug: 'GB', label: 'United Kingdom', isEU: true },
      { slug: 'GD', label: 'Grenada' },
      { slug: 'GE', label: 'Georgia' },
      { slug: 'GF', label: 'French Guiana' },
      { slug: 'GG', label: 'Guernsey' },
      { slug: 'GH', label: 'Ghana' },
      { slug: 'GI', label: 'Gibraltar' },
      { slug: 'GL', label: 'Greenland' },
      { slug: 'GM', label: 'Gambia' },
      { slug: 'GN', label: 'Guinea' },
      { slug: 'GP', label: 'Guadeloupe' },
      { slug: 'GQ', label: 'Equatorial Guinea' },
      { slug: 'GR', label: 'Greece', isEU: true },
      { slug: 'GS', label: 'South Georgia and the South Sandwich Islands' },
      { slug: 'GT', label: 'Guatemala' },
      { slug: 'GU', label: 'Guam' },
      { slug: 'GW', label: 'Guinea-Bissau' },
      { slug: 'GY', label: 'Guyana' },
      { slug: 'HK', label: 'Hong Kong SAR China' },
      { slug: 'HK', label: 'Hong Kong' },
      { slug: 'HM', label: 'Heard Island and McDonald Islands' },
      { slug: 'HN', label: 'Honduras' },
      { slug: 'HR', label: 'Croatia', isEU: true },
      { slug: 'HT', label: 'Haiti' },
      { slug: 'HU', label: 'Hungary', isEU: true },
      { slug: 'IC', label: 'Canary Islands' },
      { slug: 'ID', label: 'Indonesia' },
      { slug: 'IE', label: 'Ireland', isEU: true },
      { slug: 'IL', label: 'Israel' },
      { slug: 'IM', label: 'Isle of Man' },
      { slug: 'IN', label: 'India' },
      { slug: 'IO', label: 'British Indian Ocean Territory' },
      { slug: 'IQ', label: 'Iraq' },
      { slug: 'IR', label: 'Iran' },
      { slug: 'IS', label: 'Iceland' },
      { slug: 'IT', label: 'Italy', isEU: true },
      { slug: 'JE', label: 'Jersey' },
      { slug: 'JM', label: 'Jamaica' },
      { slug: 'JO', label: 'Jordan' },
      { slug: 'JP', label: 'Japan' },
      { slug: 'JT', label: 'Johnston Island' },
      { slug: 'KE', label: 'Kenya' },
      { slug: 'KG', label: 'Kyrgyzstan' },
      { slug: 'KH', label: 'Cambodia' },
      { slug: 'KI', label: 'Kiribati' },
      { slug: 'KM', label: 'Comoros' },
      { slug: 'KN', label: 'Saint Kitts and Nevis' },
      { slug: 'KP', label: 'North Korea' },
      { slug: 'KR', label: 'South Korea' },
      { slug: 'KW', label: 'Kuwait' },
      { slug: 'KY', label: 'Cayman Islands' },
      { slug: 'KZ', label: 'Kazakhstan' },
      { slug: 'LA', label: 'Laos' },
      { slug: 'LB', label: 'Lebanon' },
      { slug: 'LC', label: 'Saint Lucia' },
      { slug: 'LI', label: 'Liechtenstein' },
      { slug: 'LK', label: 'Sri Lanka' },
      { slug: 'LR', label: 'Liberia' },
      { slug: 'LS', label: 'Lesotho' },
      { slug: 'LT', label: 'Lithuania', isEU: true },
      { slug: 'LU', label: 'Luxembourg', isEU: true },
      { slug: 'LV', label: 'Latvia', isEU: true },
      { slug: 'LY', label: 'Libya' },
      { slug: 'MA', label: 'Morocco' },
      { slug: 'MC', label: 'Monaco' },
      { slug: 'MD', label: 'Moldova' },
      { slug: 'ME', label: 'Montenegro' },
      { slug: 'MF', label: 'Saint Martin' },
      { slug: 'MG', label: 'Madagascar' },
      { slug: 'MH', label: 'Marshall Islands' },
      { slug: 'MI', label: 'Midway Islands' },
      { slug: 'MK', label: 'Macedonia' },
      { slug: 'MK', label: 'Macedonia [FYROM]' },
      { slug: 'ML', label: 'Mali' },
      { slug: 'MM', label: 'Myanmar [Burma]' },
      { slug: 'MN', label: 'Mongolia' },
      { slug: 'MO', label: 'Macau SAR China' },
      { slug: 'MO', label: 'Macau' },
      { slug: 'MP', label: 'Northern Mariana Islands' },
      { slug: 'MQ', label: 'Martinique' },
      { slug: 'MR', label: 'Mauritania' },
      { slug: 'MS', label: 'Montserrat' },
      { slug: 'MT', label: 'Malta', isEU: true },
      { slug: 'MU', label: 'Mauritius' },
      { slug: 'MV', label: 'Maldives' },
      { slug: 'MW', label: 'Malawi' },
      { slug: 'MX', label: 'Mexico' },
      { slug: 'MY', label: 'Malaysia' },
      { slug: 'MZ', label: 'Mozambique' },
      { slug: 'NA', label: 'Namibia' },
      { slug: 'NC', label: 'New Caledonia' },
      { slug: 'NE', label: 'Niger' },
      { slug: 'NF', label: 'Norfolk Island' },
      { slug: 'NG', label: 'Nigeria' },
      { slug: 'NI', label: 'Nicaragua' },
      { slug: 'NL', label: 'Netherlands', isEU: true },
      { slug: 'NO', label: 'Norway' },
      { slug: 'NP', label: 'Nepal' },
      { slug: 'NQ', label: 'Dronning Maud Land' },
      { slug: 'NR', label: 'Nauru' },
      { slug: 'NU', label: 'Niue' },
      { slug: 'NZ', label: 'New Zealand' },
      { slug: 'OM', label: 'Oman' },
      { slug: 'PA', label: 'Panama' },
      { slug: 'PC', label: 'Pacific Islands Trust Territory' },
      { slug: 'PE', label: 'Peru' },
      { slug: 'PF', label: 'French Polynesia' },
      { slug: 'PG', label: 'Papua New Guinea' },
      { slug: 'PH', label: 'Philippines' },
      { slug: 'PK', label: 'Pakistan' },
      { slug: 'PL', label: 'Poland', isEU: true },
      { slug: 'PM', label: 'Saint Pierre and Miquelon' },
      { slug: 'PN', label: 'Pitcairn Islands' },
      { slug: 'PR', label: 'Puerto Rico' },
      { slug: 'PS', label: 'Palestinian Territories' },
      { slug: 'PT', label: 'Portugal', isEU: true },
      { slug: 'PU', label: 'U.S. Miscellaneous Pacific Islands' },
      { slug: 'PW', label: 'Palau' },
      { slug: 'PY', label: 'Paraguay' },
      { slug: 'PZ', label: 'Panama Canal Zone' },
      { slug: 'QA', label: 'Qatar' },
      { slug: 'QO', label: 'Outlying Oceania' },
      { slug: 'RE', label: 'Réunion' },
      { slug: 'RO', label: 'Romania', isEU: true },
      { slug: 'RS', label: 'Serbia' },
      { slug: 'RU', label: 'Russia' },
      { slug: 'RW', label: 'Rwanda' },
      { slug: 'SA', label: 'Saudi Arabia' },
      { slug: 'SB', label: 'Solomon Islands' },
      { slug: 'SC', label: 'Seychelles' },
      { slug: 'SD', label: 'Sudan' },
      { slug: 'SE', label: 'Sweden', isEU: true },
      { slug: 'SG', label: 'Singapore' },
      { slug: 'SH', label: 'Saint Helena' },
      { slug: 'SI', label: 'Slovenia', isEU: true },
      { slug: 'SJ', label: 'Svalbard and Jan Mayen' },
      { slug: 'SK', label: 'Slovakia', isEU: true },
      { slug: 'SL', label: 'Sierra Leone' },
      { slug: 'SM', label: 'San Marino' },
      { slug: 'SN', label: 'Senegal' },
      { slug: 'SO', label: 'Somalia' },
      { slug: 'SR', label: 'Suriname' },
      { slug: 'ST', label: 'São Tomé and Príncipe' },
      { slug: 'SV', label: 'El Salvador' },
      { slug: 'SY', label: 'Syria' },
      { slug: 'SZ', label: 'Swaziland' },
      { slug: 'TA', label: 'Tristan da Cunha' },
      { slug: 'TC', label: 'Turks and Caicos Islands' },
      { slug: 'TD', label: 'Chad' },
      { slug: 'TF', label: 'French Southern Territories' },
      { slug: 'TG', label: 'Togo' },
      { slug: 'TH', label: 'Thailand' },
      { slug: 'TJ', label: 'Tajikistan' },
      { slug: 'TK', label: 'Tokelau' },
      { slug: 'TL', label: 'Timor-Leste' },
      { slug: 'TL', label: 'East Timor' },
      { slug: 'TM', label: 'Turkmenistan' },
      { slug: 'TN', label: 'Tunisia' },
      { slug: 'TO', label: 'Tonga' },
      { slug: 'TR', label: 'Turkey' },
      { slug: 'TT', label: 'Trinidad and Tobago' },
      { slug: 'TV', label: 'Tuvalu' },
      { slug: 'TW', label: 'Taiwan' },
      { slug: 'TZ', label: 'Tanzania' },
      { slug: 'UA', label: 'Ukraine' },
      { slug: 'UG', label: 'Uganda' },
      { slug: 'UM', label: 'U.S. Minor Outlying Islands' },
      { slug: 'US', label: 'United States' },
      { slug: 'UY', label: 'Uruguay' },
      { slug: 'UZ', label: 'Uzbekistan' },
      { slug: 'VA', label: 'Vatican City' },
      { slug: 'VC', label: 'Saint Vincent and the Grenadines' },
      { slug: 'VD', label: 'North Vietnam' },
      { slug: 'VE', label: 'Venezuela' },
      { slug: 'VG', label: 'British Virgin Islands' },
      { slug: 'VI', label: 'U.S. Virgin Islands' },
      { slug: 'VN', label: 'Vietnam' },
      { slug: 'VU', label: 'Vanuatu' },
      { slug: 'WF', label: 'Wallis and Futuna' },
      { slug: 'WK', label: 'Wake Island' },
      { slug: 'WS', label: 'Samoa' },
      { slug: 'YD', label: 'People\'s Democratic Republic of Yemen' },
      { slug: 'YE', label: 'Yemen' },
      { slug: 'YT', label: 'Mayotte' },
      { slug: 'ZA', label: 'South Africa' },
      { slug: 'ZM', label: 'Zambia' },
      { slug: 'ZW', label: 'Zimbabwe' }
    ]

    return {
      get: function () {
        return _.sortBy(countries, function (elem) {
          if (elem.slug === 'US') return 0
          else if (elem.slug === 'GB') return 1
          else if (elem.slug === 'CA') return 2
          else if (elem.slug === 'FR') return 3
          else if (elem.slug === 'AU') return 4
          else return 5
        })
      }
    }
  })
